-- ============================================================
-- Habit Tracker — Idempotent Column Migration
-- Ensures every column referenced in the application code
-- exists in the database. Safe to run multiple times.
-- Generated by cross-referencing all controller files against
-- the schema definition.
-- ============================================================

-- ── users ───────────────────────────────────────────────────
-- Columns referenced: id, name, email, created_at
-- (password_hash is in schema but not queried by controllers)
ALTER TABLE users ADD COLUMN IF NOT EXISTS name          VARCHAR(100)  NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS email         VARCHAR(255)  NOT NULL DEFAULT '' UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255)  NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW();

-- ── categories ──────────────────────────────────────────────
-- Columns referenced: id, user_id, name, color, icon, created_at
ALTER TABLE categories ADD COLUMN IF NOT EXISTS user_id    UUID         NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS name       VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS color      VARCHAR(7)   NOT NULL DEFAULT '#6C63FF';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon       VARCHAR(50);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW();

-- ── habits ──────────────────────────────────────────────────
-- Columns referenced: id, user_id, category_id, name, description,
--                     frequency, target_days, color, icon, is_active, created_at
ALTER TABLE habits ADD COLUMN IF NOT EXISTS user_id     UUID         NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS category_id UUID;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS name        VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS frequency   VARCHAR(20)  NOT NULL DEFAULT 'daily';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS target_days INTEGER[]    NOT NULL DEFAULT '{1,2,3,4,5,6,7}';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS color       VARCHAR(7)   NOT NULL DEFAULT '#6C63FF';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS icon        VARCHAR(50);
ALTER TABLE habits ADD COLUMN IF NOT EXISTS is_active   BOOLEAN      NOT NULL DEFAULT TRUE;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW();

-- ── habit_logs ──────────────────────────────────────────────
-- Columns referenced: id, habit_id, user_id, completed_at, note, created_at
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS habit_id     UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS user_id      UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS completed_at DATE        NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS note         TEXT;
ALTER TABLE habit_logs ADD COLUMN IF NOT EXISTS created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ── tasks ───────────────────────────────────────────────────
-- Columns referenced: id, user_id, category_id, title, description,
--                     due_date, priority, is_completed, is_archived, created_at
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id      UUID         NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS category_id  UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS title        VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS description  TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS due_date     DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority     VARCHAR(10)  NOT NULL DEFAULT 'medium';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_completed BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_archived  BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW();

-- ── task_logs ───────────────────────────────────────────────
-- Columns referenced: id, task_id, user_id, action, created_at
ALTER TABLE task_logs ADD COLUMN IF NOT EXISTS task_id    UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE task_logs ADD COLUMN IF NOT EXISTS user_id    UUID        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE task_logs ADD COLUMN IF NOT EXISTS action     VARCHAR(20) NOT NULL DEFAULT 'created';
ALTER TABLE task_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ── Supporting indexes (idempotent) ─────────────────────────
CREATE INDEX IF NOT EXISTS idx_users_email            ON users(email);
CREATE INDEX IF NOT EXISTS idx_categories_user_id     ON categories(user_id);
CREATE INDEX IF NOT EXISTS idx_habits_user_id         ON habits(user_id);
CREATE INDEX IF NOT EXISTS idx_habits_is_active       ON habits(is_active);
CREATE INDEX IF NOT EXISTS idx_habit_logs_user_id     ON habit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_habit_logs_habit_id    ON habit_logs(habit_id);
CREATE INDEX IF NOT EXISTS idx_habit_logs_completed_at ON habit_logs(completed_at);
CREATE INDEX IF NOT EXISTS idx_tasks_user_id          ON tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date         ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_is_completed     ON tasks(is_completed);
CREATE INDEX IF NOT EXISTS idx_tasks_is_archived      ON tasks(is_archived);
CREATE INDEX IF NOT EXISTS idx_task_logs_task_id      ON task_logs(task_id);
CREATE INDEX IF NOT EXISTS idx_task_logs_user_id      ON task_logs(user_id);
